import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/app/**/*.{ts,tsx,js,jsx,mdx}",
    "./src/components/**/*.{ts,tsx,js,jsx,mdx}",
    "./src/lib/**/*.{ts,tsx,js,jsx,mdx}",
    "./src/store/**/*.{ts,tsx,js,jsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "rgb(var(--color-canvas) / <alpha-value>)",
        panel: "rgb(var(--color-panel) / <alpha-value>)",
        panelAlt: "rgb(var(--color-panel-alt) / <alpha-value>)",
        text: "rgb(var(--color-text) / <alpha-value>)",
        textMuted: "rgb(var(--color-text-muted) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        accentSoft: "rgb(var(--color-accent-soft) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "secondary-fixed": "#dbe4ea",
        "on-background": "#191c1e",
        "background": "#f7f9fb",
        "on-surface-variant": "#434655",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0053db",
        "secondary-container": "#dbe4ea",
        "primary-container": "#2563eb",
        "surface-container": "#eceef0",
        "on-secondary-container": "#5d666b",
        "tertiary": "#3e3fcc",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "on-error": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-container": "#f1eeff",
        "primary": "#004ac6",
        "outline-variant": "#c3c6d7",
        "on-tertiary-fixed": "#07006c",
        "secondary": "#576065",
        "on-primary-fixed-variant": "#003ea8",
        "surface-bright": "#f7f9fb",
        "on-surface": "#191c1e",
        "primary-fixed": "#dbe1ff",
        "on-primary-container": "#eeefff",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#141d21",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#585be6",
        "surface": "#f7f9fb",
        "on-primary-fixed": "#00174b",
        "tertiary-fixed": "#e1e0ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bfc8ce",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#3f484d",
        "outline": "#737686",
      },
      fontSize: {
        "headline-xl-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      fontFamily: {
        heading: ["var(--font-heading)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
        "headline-xl-mobile": ["var(--font-heading)"],
        "headline-xl": ["var(--font-heading)"],
        "headline-lg-mobile": ["var(--font-heading)"],
        "body-md": ["var(--font-body)"],
        "label-sm": ["var(--font-body)"],
        "headline-lg": ["var(--font-heading)"],
        "label-md": ["var(--font-body)"],
        "body-lg": ["var(--font-body)"],
      },
      spacing: {
        "margin-desktop": "48px",
        "margin-mobile": "16px",
      },
      boxShadow: {
        glow: "0 18px 60px -18px rgba(14, 116, 144, 0.45)",
      },
      backgroundImage: {
        "page-grid":
          "linear-gradient(to right, rgb(var(--color-border) / 0.25) 1px, transparent 1px), linear-gradient(to bottom, rgb(var(--color-border) / 0.25) 1px, transparent 1px)",
      },
    },
  },
  plugins: [],
};

export default config;
